name: Snyk Project Import (GitHub Cloud)

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Daily at 00:00 UTC (adjust as needed)
  push:
    branches:
      - main # Or your default branch

jobs:
  import_projects:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code (if needed for local imports)
      #   uses: actions/checkout@v3
      #   with:
      #     path: my-repo # Optional: Specify a path if needed

      # - name: Set up Python (if needed for other scripting)
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x' # Or your preferred version

      - name: Install jq (for JSON processing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Snyk API import script
        env:
          SNYK_API_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.ORG_ID }}
          INTEGRATION_ID: ${{ secrets.SNYK_INTEGRATION_ID }} # GitHub Integration ID
          PROJECT_NAME: ${{ github.repository }} # Default project name (owner/repo)
        run: |
          #!/bin/bash

          SNYK_API_TOKEN="$SNYK_API_TOKEN"
          SNYK_ORG_ID="$SNYK_ORG_ID"
          INTEGRATION_ID="$INTEGRATION_ID"
          PROJECT_NAME="$PROJECT_NAME"

          import_target() {
            local target_json="$1"
            curl -s -H "Authorization: token ${SNYK_API_TOKEN}" \
                 -H "Content-Type: application/json" \
                 -d "${target_json}" \
                 "https://api.snyk.io/rest/org/${SNYK_ORG_ID}/integrations/${INTEGRATION_ID}/import"
          }

          # --- Target Definitions (GitHub Cloud) ---
          github_target='{
            "target": {
              "url": "https://github.com/${{ github.repository }}", # Use GitHub Actions context
              "branch": "main" # Or ${{ github.ref_name }} for the triggering branch
            }
          }'

          github_commit_target='{
            "target": {
              "url": "https://github.com/${{ github.repository }}",
              "commit": "${{ github.sha }}" # Use GitHub Actions context for commit hash
            }
          }'

          # --- Import and Rename (same as before) ---
          import_and_rename() {
            local target_json="$1"
            echo "$target_json"
            local default_project_name=$(echo "$target_json" | jq -r '.target.url | rtrimstr("https://") | rtrimstr("http://")')
            # default_project_name="${default_project_name//\//-}" # Replace / with - for name

            echo "$default_project_name"

            response=$(import_target "$target_json")
            status_code=$(echo "$response" | jq -r '.statusCode')

            if [[ "$status_code" -ne 200 ]]; then
              echo "Error importing target: $response"
              exit 1
            fi

            sleep 5 # Adjust sleep time as needed

            PROJECT_ID=$(curl -s -H "Authorization: token ${SNYK_API_TOKEN}" \
                            "https://api.snyk.io/rest/org/${SNYK_ORG_ID}/projects" | \
                            jq -r ".projects | select(.name == \"$default_project_name\").id")

            if [[ -n "$PROJECT_ID" ]]; then
              curl -X PATCH -s -H "Authorization: token ${SNYK_API_TOKEN}" \
                   -H "Content-Type: application/json" \
                   -d "{\"name\": \"$PROJECT_NAME\"}" \
                   "https://api.snyk.io/rest/org/${SNYK_ORG_ID}/project/${PROJECT_ID}"
              echo "Project renamed to $PROJECT_NAME"
            else
              echo "Error: Could not find project ID after import."
              exit 1
            fi
          }

          # Import and rename each target
          import_and_rename "$github_target"
          import_and_rename "$github_commit_target"

          echo "Import and rename scripts finished."
